/**
 * ============================================================================
 *  CAPSULE — CHATBOT KNOWLEDGE BASE
 *
 *  Builds the assistant's entire knowledge base from the same content files
 *  that render the website. This is the whole point of the design: the
 *  chatbot physically cannot know a price the site does not show, because
 *  both read from src/content/pricing.ts.
 *
 *  YOU DO NOT EDIT THIS FILE TO CHANGE WHAT THE CHATBOT KNOWS.
 *  Edit the content files (pricing.ts, services.ts, faqs.ts, pages.ts,
 *  legal.ts, workspace.ts, site.ts) and the chatbot updates with the site.
 *
 *  ── Why the whole knowledge base, and not vector search ──
 *  The corpus is roughly 15,000 tokens. That fits in a cached system prompt,
 *  which means the assistant sees ALL of it on every question — no retrieval
 *  step, so no chance of retrieving the wrong passage and answering from it.
 *  Prompt caching keeps the cost of resending it negligible.
 *
 *  If the content grows past KB_TOKEN_CEILING the server logs a warning: at
 *  that point add a retrieval step rather than letting the prompt balloon.
 *
 *  ── Cache stability ──
 *  The output must be byte-identical between requests or prompt caching
 *  silently stops working. Never put a timestamp, a random value or an
 *  unsorted object into this string.
 * ============================================================================
 */

import { faqs } from "@/content/faqs";
import { about, howItWorks, location, partners } from "@/content/pages";
import { acceptableUse, privacy, terms } from "@/content/legal";
import {
  PRICING_DISCLAIMER,
  TERMS,
  formatPeso,
  publishedAddressTiers,
  publishedRooms,
  publishedWorkspace,
} from "@/content/pricing";
import { services } from "@/content/services";
import { site } from "@/content/site";
import { workspacePages } from "@/content/workspace";

/** Above this, stop sending the whole corpus and add retrieval. */
export const KB_TOKEN_CEILING = 60_000;

const NL = "\n";

function heading(text: string): string {
  return `${NL}## ${text}${NL}`;
}

function bullets(items: readonly string[]): string {
  return items.map((item) => `- ${item}`).join(NL);
}

/* -------------------------------------------------------------- the company */

function buildIdentity(): string {
  return [
    heading("About Capsule"),
    `Capsule is a virtual-office service at ${site.address.oneLine}. It provides a business address, mail and document handling, meeting rooms and serviced workspace, with a registered-address option on eligible packages.`,
    "Capsule does NOT provide, coordinate or advise on: company registration or incorporation, SEC or BIR filings, business permits, bookkeeping, accounting, tax, payroll, corporate secretarial work, or business-setup consulting. Those are the client's own responsibility, with their own advisers.",
    `Operator: ${site.operator.relationship}`,
    site.operator.secRegistrationNo !== "TODO"
      ? `SEC registration number: ${site.operator.secRegistrationNo}`
      : "",
    "",
    "Office hours:",
    `- ${site.hours.weekdays}`,
    `- ${site.hours.saturday}`,
    `- ${site.hours.note}`,
    "",
    "Contact channels:",
    `- Telephone: ${site.contact.landline}`,
    `- Email: ${site.contact.email}`,
    `- Viber: ${site.contact.viber}`,
    `- WhatsApp: ${site.contact.whatsapp}`,
    "",
    "Verified facts about the premises:",
    bullets(site.facts.map((f) => `${f.value} — ${f.label}`)),
    "",
    about.intro,
    ...about.sections.map((s) => `${NL}### ${s.heading}${NL}${s.body.join(NL)}`),
  ]
    .filter(Boolean)
    .join(NL);
}

/* ------------------------------------------------------------------ pricing */

function buildPricing(): string {
  const lines: string[] = [heading("Pricing — authoritative")];

  if (PRICING_DISCLAIMER) {
    lines.push(
      `IMPORTANT PRICING STATUS: ${PRICING_DISCLAIMER}`,
      "State this qualification whenever you quote a price.",
      "",
    );
  }

  lines.push("### Business address tiers");
  for (const tier of publishedAddressTiers) {
    lines.push(
      `${NL}**${tier.name}**`,
      `- Best for: ${tier.bestFor}`,
      `- Price on a 12-month term: ${formatPeso(tier.price12)} per month`,
      `- Price on a rolling monthly term: ${formatPeso(tier.priceMonthly)} per month`,
      `- May this package's address be used as the client's registered business address? ${
        tier.registrationEligible
          ? "YES — subject to an approved application, documents and our acceptable use policy. Capsule provides the address only; it does not make any filing or registration on the client's behalf."
          : "NO — this package is for correspondence only."
      }`,
      "- Includes:",
      bullets(tier.features),
    );
  }

  lines.push(
    `${NL}### Contract terms offered`,
    bullets(TERMS.map((t) => `${t.label} — ${t.discountNote}`)),
  );

  lines.push(`${NL}### Workspace`);
  for (const product of publishedWorkspace) {
    lines.push(
      `${NL}**${product.name}** — ${
        product.price === null
          ? "priced on application, no published rate"
          : `${formatPeso(product.price)} ${product.unit}`
      }`,
      `- Best for: ${product.bestFor}`,
      bullets(product.features),
    );
  }

  lines.push(`${NL}### Meeting rooms`);
  for (const room of publishedRooms) {
    lines.push(
      `- **${room.name}** (${room.capacity}): ${
        room.rate === null
          ? "no published hourly rate — available to members and room bookers"
          : `${formatPeso(room.rate)} per hour, ${formatPeso(room.memberRate)} per hour for members`
      }. ${room.note}`,
    );
  }

  return lines.filter(Boolean).join(NL);
}

/* ----------------------------------------------------------------- services */

function buildServices(): string {
  const lines: string[] = [heading("Services")];

  for (const service of services) {
    lines.push(
      `${NL}### ${service.name}  (page: /services/${service.slug})`,
      "Provided directly by Capsule from its own floor.",
      service.intro,
      "Key points:",
      bullets(service.highlights),
      ...service.sections.map((s) => `${NL}${s.heading}: ${s.body.join(" ")}`),
    );
  }

  for (const page of workspacePages) {
    lines.push(
      `${NL}### ${page.name}  (page: /workspace/${page.slug})`,
      page.intro,
      ...page.sections.map((s) => `${NL}${s.heading}: ${s.body.join(" ")}`),
    );
  }

  return lines.join(NL);
}

/* ----------------------------------------------------- location & processes */

function buildLocationAndProcess(): string {
  return [
    heading("The office and how to find it"),
    location.intro,
    "Facilities on the floor:",
    bullets(location.facilities.map((f) => `${f.name}: ${f.detail}`)),
    ...location.gettingHere.map((g) => `${NL}${g.heading}: ${g.body}`),

    heading("How to sign up"),
    howItWorks.intro,
    ...howItWorks.steps.map((s) => `${s.n}. ${s.title} — ${s.body}`),
    howItWorks.note,

    heading("For referring partners and consultants"),
    partners.intro,
    ...partners.forPartners.map((p) => `${p.heading}: ${p.body}`),
  ].join(NL);
}

/* --------------------------------------------------------------------- FAQs */

function buildFaqs(): string {
  const lines: string[] = [heading("Frequently asked questions")];
  for (const faq of faqs) {
    lines.push(`${NL}**Q: ${faq.q}**`, `A: ${faq.a.join(" ")}`);
  }
  return lines.join(NL);
}

/* -------------------------------------------------------------------- legal */

function buildPolicies(): string {
  const docs = [
    { name: "Terms of Service", doc: terms },
    { name: "Acceptable Use Policy", doc: acceptableUse },
    { name: "Privacy Policy", doc: privacy },
  ];

  const lines: string[] = [heading("Policies")];
  for (const { name, doc } of docs) {
    lines.push(`${NL}### ${name}`, doc.intro);
    for (const section of doc.sections) {
      lines.push(`${section.heading}: ${section.body.join(" ")}`);
    }
  }
  return lines.join(NL);
}

/* ------------------------------------------------------------------- export */

/**
 * Built once at module load. Frozen string, byte-stable between requests,
 * which is what makes prompt caching work.
 */
export const KNOWLEDGE_BASE: string = [
  "# CAPSULE KNOWLEDGE BASE",
  "Everything below is the authoritative record of Capsule's services, prices, policies and premises. It is generated from the website's own content, so it always matches what a visitor can see on the site.",
  buildIdentity(),
  buildPricing(),
  buildServices(),
  buildLocationAndProcess(),
  buildFaqs(),
  buildPolicies(),
].join(NL);

/** Rough token estimate. Good enough for a size guard; not billing-accurate. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 3.6);
}

export const KB_ESTIMATED_TOKENS = estimateTokens(KNOWLEDGE_BASE);

if (KB_ESTIMATED_TOKENS > KB_TOKEN_CEILING) {
  console.warn(
    `[knowledge] The knowledge base is now ~${KB_ESTIMATED_TOKENS} tokens, above the ${KB_TOKEN_CEILING} ceiling. ` +
      "Sending all of it on every request is getting expensive — add a retrieval step that selects relevant sections instead.",
  );
}
