/**
 * ============================================================================
 *  PDMN VIRTUAL OFFICE — CHATBOT KNOWLEDGE BASE
 *
 *  Builds the assistant's entire knowledge base from the same content files
 *  that render the website. This is the whole point of the design: the
 *  chatbot physically cannot know a price the site does not show, because
 *  both read from src/content/pricing.ts.
 *
 *  YOU DO NOT EDIT THIS FILE TO CHANGE WHAT THE CHATBOT KNOWS.
 *  Edit the content files (pricing.ts, services.ts, faqs.ts, pages.ts,
 *  legal.ts, site.ts) and the chatbot updates with the site.
 *
 *  ── Why the whole knowledge base, and not vector search ──
 *  The corpus is roughly 15,000 tokens. That fits in a cached system prompt,
 *  which means the assistant sees ALL of it on every question — no retrieval
 *  step, so no chance of retrieving the wrong passage and answering from it.
 *  Prompt caching keeps the cost of resending it negligible.
 *
 *  If the content grows past KB_TOKEN_CEILING the server logs a warning: at
 *  that point add a retrieval step rather than letting the prompt balloon.
 *
 *  ── Cache stability ──
 *  The output must be byte-identical between requests or prompt caching
 *  silently stops working. Never put a timestamp, a random value or an
 *  unsorted object into this string.
 * ============================================================================
 */

import { faqs } from "@/content/faqs";
import { about, howItWorks, location } from "@/content/pages";
import { acceptableUse, privacy, terms } from "@/content/legal";
import { publishedAddressTiers, packageRate, VIP_RATE_NOTE } from "@/content/pricing";
import { services } from "@/content/services";
import { site } from "@/content/site";

/** Above this, stop sending the whole corpus and add retrieval. */
export const KB_TOKEN_CEILING = 60_000;

const NL = "\n";

function heading(text: string): string {
  return `${NL}## ${text}${NL}`;
}

function bullets(items: readonly string[]): string {
  return items.map((item) => `- ${item}`).join(NL);
}

/* -------------------------------------------------------------- the company */

function buildIdentity(): string {
  return [
    heading("About PDMN Virtual Office"),
    `PDMN Virtual Office is at ${site.address.oneLine}. PDMN Virtual Office provides a professional business address and physical-office support in Makati. Registration and compliance support is through the address and facilities agreed for your package; government approvals are not guaranteed.`,
    "Support is through the address and physical facilities agreed for the package. Do not promise filing, representation, legal advice or government approval.",
    `Operator: ${site.operator.relationship}`,
    site.operator.secRegistrationNo !== "TODO"
      ? `SEC registration number: ${site.operator.secRegistrationNo}`
      : "",
    "",
    "Office hours:",
    `- ${site.hours.weekdays}`,
    `- ${site.hours.saturday}`,
    `- ${site.hours.note}`,
    "",
    "Contact channels:",
    `- Telephone: ${site.contact.landline}`,
    `- Email: ${site.contact.email}`,
    `- Viber: ${site.contact.viber}`,
    `- WhatsApp: ${site.contact.whatsapp}`,
    "",
    "Verified facts about the premises:",
    bullets(site.facts.map((f) => `${f.value} — ${f.label}`)),
    "",
    about.intro,
    ...about.sections.map((s) => `${NL}### ${s.heading}${NL}${s.body.join(NL)}`),
  ]
    .filter(Boolean)
    .join(NL);
}

/* ------------------------------------------------------------------ pricing */

function buildPricing(): string {
  return [heading("Packages"), VIP_RATE_NOTE, ...publishedAddressTiers.map(tier => `${tier.name}: ${packageRate(tier)}. ${tier.bestFor}\n${bullets(tier.features)}`)].join(NL);
}

/* ----------------------------------------------------------------- services */

function buildServices(): string {
  const lines: string[] = [heading("Services")];

  for (const service of services) {
    lines.push(
      `${NL}### ${service.name}  (page: /services/${service.slug})`,
      "Facility locations and availability are confirmed for the agreed requirements.",
      service.intro,
      "Key points:",
      bullets(service.highlights),
      ...service.sections.map((s) => `${NL}${s.heading}: ${s.body.join(" ")}`),
    );
  }

  return lines.join(NL);
}

/* ----------------------------------------------------- location & processes */

function buildLocationAndProcess(): string {
  return [
    heading("The office and how to find it"),
    location.intro,
    "Facilities on the floor:",
    bullets(location.facilities.map((f) => `${f.name}: ${f.detail}`)),
    ...location.gettingHere.map((g) => `${NL}${g.heading}: ${g.body}`),

    heading("How to sign up"),
    howItWorks.intro,
    ...howItWorks.steps.map((s) => `${s.n}. ${s.title} — ${s.body}`),
    howItWorks.note,
  ].join(NL);
}

/* --------------------------------------------------------------------- FAQs */

function buildFaqs(): string {
  const lines: string[] = [heading("Frequently asked questions")];
  for (const faq of faqs) {
    lines.push(`${NL}**Q: ${faq.q}**`, `A: ${faq.a.join(" ")}`);
  }
  return lines.join(NL);
}

/* -------------------------------------------------------------------- legal */

function buildPolicies(): string {
  const docs = [
    { name: "Terms of Service", doc: terms },
    { name: "Acceptable Use Policy", doc: acceptableUse },
    { name: "Privacy Policy", doc: privacy },
  ];

  const lines: string[] = [heading("Policies")];
  for (const { name, doc } of docs) {
    lines.push(`${NL}### ${name}`, doc.intro);
    for (const section of doc.sections) {
      lines.push(`${section.heading}: ${section.body.join(" ")}`);
    }
  }
  return lines.join(NL);
}

/* ------------------------------------------------------------------- export */

/**
 * Built once at module load. Frozen string, byte-stable between requests,
 * which is what makes prompt caching work.
 */
export const KNOWLEDGE_BASE: string = [
  "# PDMN VIRTUAL OFFICE KNOWLEDGE BASE",
  "Everything below is the authoritative record of our services, prices, policies and premises. It is generated from the website's own content, so it always matches what a visitor can see on the site.",
  buildIdentity(),
  buildPricing(),
  buildServices(),
  buildLocationAndProcess(),
  buildFaqs(),
  buildPolicies(),
].join(NL);

/** Rough token estimate. Good enough for a size guard; not billing-accurate. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 3.6);
}

export const KB_ESTIMATED_TOKENS = estimateTokens(KNOWLEDGE_BASE);

if (KB_ESTIMATED_TOKENS > KB_TOKEN_CEILING) {
  console.warn(
    `[knowledge] The knowledge base is now ~${KB_ESTIMATED_TOKENS} tokens, above the ${KB_TOKEN_CEILING} ceiling. ` +
      "Sending all of it on every request is getting expensive — add a retrieval step that selects relevant sections instead.",
  );
}

