import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../src/server.mjs';
import { Store } from '../src/store.mjs';
import { completeState } from './helpers.mjs';

test('HTTP login, role enforcement, CSRF, validation, and session revocation', async t => {
  const store = new Store(':memory:');
  const app = createApp({ store, origin: 'http://127.0.0.1:3400', setupToken: 'test-only-setup-code' });
  await new Promise(resolve => app.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => app.close(resolve)); store.close(); });
  const base = `http://127.0.0.1:${app.address().port}`;
  const call = (path, body, cookie = '', csrf = '', origin = 'http://127.0.0.1:3400') => fetch(`${base}${path}`, { method: body ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', Origin: origin, Cookie: cookie, 'X-CSRF-Token': csrf }, body: body ? JSON.stringify(body) : undefined });
  assert.equal((await call('/api/state')).status, 401);
  assert.equal((await call('/api/setup', { token: 'wrong' })).status, 403);
  assert.equal((await call('/api/setup', { token: 'test-only-setup-code', username: 'admin', password: 'strong-test-password' })).status, 201);
  assert.equal((await call('/api/setup', { token: 'test-only-setup-code', username: 'admin2', password: 'strong-test-password' })).status, 409);
  const response = await call('/api/login', { username: 'admin', password: 'strong-test-password' });
  assert.equal(response.status, 200);
  const cookie = response.headers.get('set-cookie').split(';')[0], auth = await response.json();
  assert.match(response.headers.get('set-cookie'), /HttpOnly/);
  assert.equal((await call('/api/state', null, cookie)).status, 200);
  assert.equal((await call('/api/records/holidays', {}, cookie)).status, 403);
  assert.equal((await call('/api/records/holidays', {}, cookie, auth.csrf, 'https://attacker.example')).status, 403);
  assert.equal((await call('/api/records/holidays', { id: 'x' }, cookie, auth.csrf)).status, 400);
  assert.equal((await call('/api/users', { username: 'viewer', password: 'strong-viewer-password', role: 'viewer' }, cookie, auth.csrf)).status, 201);
  const v = await call('/api/login', { username: 'viewer', password: 'strong-viewer-password' });
  const vc = v.headers.get('set-cookie').split(';')[0], va = await v.json();
  assert.equal((await call('/api/records/holidays', {}, vc, va.csrf)).status, 403);
  assert.equal((await call('/api/session', null, cookie)).status, 200);
  assert.equal((await call('/', null, cookie)).status, 200);
  assert.equal((await call('/app.js', null, cookie)).status, 200);
  assert.equal((await call('/style.css', null, cookie)).status, 200);
  assert.equal((await call('/api/users', null, cookie)).status, 200);
  assert.equal((await call('/api/audit', null, cookie)).status, 200);
  assert.equal((await call('/api/runs/missing', null, cookie)).status, 404);
  store.write(completeState());
  const previewResponse = await call('/api/payroll/preview', { start: '2026-09-01', end: '2026-09-15', pay13th: false }, cookie, auth.csrf);
  assert.equal(previewResponse.status, 200);
  const payroll = await previewResponse.json();
  assert.deepEqual(payroll.blockers, []);
  const postedResponse = await call('/api/payroll/post', { start: payroll.start, end: payroll.end, pay13th: payroll.pay13th, fingerprint: payroll.fingerprint }, cookie, auth.csrf);
  assert.equal(postedResponse.status, 200);
  const run = await postedResponse.json();
  assert.equal((await call(`/api/runs/${run.id}`, null, cookie)).status, 200);
  const workbook = await call(`/api/runs/${run.id}.xlsx`, null, cookie);
  assert.equal(workbook.status, 200);
  assert.match(workbook.headers.get('content-type'), /spreadsheetml/);
  assert.equal(new Uint8Array(await workbook.arrayBuffer())[0], 0x50);
  assert.equal((await call('/api/logout', {}, cookie, auth.csrf)).status, 200);
  assert.equal((await call('/api/state', null, cookie)).status, 401);
});
