/**
 * Drop unreferenced asset folders from the static export before packaging.
 *
 *   node scripts/prune-export.mjs
 *
 * Next copies everything in public/ into out/, whether the site uses it or
 * not. Four folders are left over from earlier work and are referenced by
 * nothing — not by source, not by any built HTML, JS, RSC payload or sitemap.
 * They were 75 MB of a 122 MB export, which is very likely why the Cloudflare
 * dashboard upload failed.
 *
 * IMPORTANT: this only touches out/, which is a build artifact regenerated by
 * every `npm run build`. It never deletes from public/. The originals stay
 * where they are — the HR project uses public/mascot-poses/ as a source, and
 * the rest are keepsakes from the previous brand.
 *
 * Before removing a folder it re-checks that nothing in the export refers to
 * it, so adding a reference later automatically protects the assets.
 */

import fs from "node:fs/promises";
import path from "node:path";

const OUT = path.join(process.cwd(), "out");

/** Unreferenced folders in the built site. Verified at runtime below. */
const CANDIDATES = [
  "the-grounds",
  "virtual-office-vip-storyboard",
  "branding",
  "mascot-poses",
  /* Logo exploration: drafts, "previous" and "revised" variants kept from the
     rebrand. The logo the site actually serves is emitted by next/image into
     _next/static/media/, so nothing under brand/ is reachable. */
  "brand",
];

/**
 * Individual leftover files, in three groups: the Next.js starter placeholders
 * that ship in every new project, preview renders from the retired "capsule"
 * name and from the logo exploration, and two README notes that are useful in
 * the repository but are not web assets.
 *
 * location-map-data.osm is the raw OpenStreetMap extract that
 * scripts/build-location-map.mjs consumes to produce location-map.svg. It is
 * build input, not something a browser ever fetches.
 *
 * Checked for references exactly as the folders are, so linking to one of these
 * later protects it automatically.
 */
const LOOSE_FILES = [
  "file.svg",
  "globe.svg",
  "next.svg",
  "vercel.svg",
  "window.svg",
  "capsule-logo-preview.png",
  "capsule-logo-inverse-preview.png",
  "capsule-logo-concept-2-preview.png",
  "capsule-logo-concept-2-inverse-preview.png",
  "pdmn-virtual-office-logo-premium.png",
  "pdmn-virtual-office-logo-premium-4x3.png",
  "pdmn-mascot.png",
  "location-map-data.osm",
  "photos/README.md",
  "photos/rooms/README.md",
];

const TEXTUAL = new Set([".html", ".js", ".txt", ".json", ".xml", ".css", ".map"]);

async function* walk(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

async function referencedIn(name, files, { isFile = false } = {}) {
  /* A folder is referenced by "name/"; a file by its own basename, which is
     what any href, src, srcset or manifest entry has to contain. */
  const needle = isFile ? path.basename(name) : `${name}/`;
  const selfPath = path.join(OUT, name);
  for (const file of files) {
    if (!TEXTUAL.has(path.extname(file))) continue;
    /* Skip the candidate itself, and anything inside the folder being tested —
       something referring to itself proves nothing. */
    if (isFile ? file === selfPath : file.includes(`${path.sep}${name}${path.sep}`)) {
      continue;
    }
    const body = await fs.readFile(file, "utf8").catch(() => "");
    if (body.includes(needle)) return path.relative(OUT, file);
  }
  return null;
}

async function dirSize(dir) {
  let total = 0;
  for await (const f of walk(dir)) total += (await fs.stat(f)).size;
  return total;
}

async function main() {
  const files = [];
  for await (const f of walk(OUT)) files.push(f);

  let freed = 0;
  for (const name of CANDIDATES) {
    const dir = path.join(OUT, name);
    try {
      await fs.access(dir);
    } catch {
      continue;
    }

    const ref = await referencedIn(name, files);
    if (ref) {
      console.log(`  KEPT     ${name}  — referenced by ${ref}`);
      continue;
    }

    const size = await dirSize(dir);
    await fs.rm(dir, { recursive: true, force: true });
    freed += size;
    console.log(`  pruned   ${name.padEnd(32)} ${(size / 1048576).toFixed(1)} MB`);
  }

  for (const name of LOOSE_FILES) {
    const target = path.join(OUT, name);
    let size;
    try {
      size = (await fs.stat(target)).size;
    } catch {
      continue;
    }

    const ref = await referencedIn(name, files, { isFile: true });
    if (ref) {
      console.log(`  KEPT     ${name}  - referenced by ${ref}`);
      continue;
    }

    await fs.rm(target, { force: true });
    freed += size;
    console.log(`  pruned   ${name.padEnd(46)} ${(size / 1024).toFixed(0)} KB`);
  }

  console.log(`\n  freed ${(freed / 1048576).toFixed(1)} MB from the export (public/ untouched)\n`);
}

main().catch((e) => {
  console.error(`\n${e.message}\n`);
  process.exitCode = 1;
});
