import { z } from 'zod';
const text = z.string().trim().min(1).max(1000);
export const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => !Number.isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v, 'Invalid date');
const optionalDate = z.union([date, z.literal('')]);
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const optionalTime = z.union([time, z.literal('')]);
const number = z.number().finite().min(0).max(1e9);
const money = number.refine(v => Math.abs(v * 100 - Math.round(v * 100)) < 0.00001, 'Use at most two decimal places');
const id = z.string().trim().regex(/^[A-Za-z0-9_-]{1,80}$/);
const flag = z.boolean();
// Contribution bracket: employee share = fixed + rate x max(0, salary - excessOver); employer share = employerFixed + employerRate x the same
// excess, plus ec (SSS Employees' Compensation, employer only). Employer fields default to 0 so tax and legacy brackets still parse.
const bracket = z.object({ from: number, to: number.nullable(), fixed: money, rate: z.number().min(0).max(1), excessOver: number, employerFixed: money.default(0), employerRate: z.number().min(0).max(1).default(0), ec: money.default(0) }).strict();
// Proof (e.g. a medical certificate) for leave types that require documents. Server-owned: set when an
// employee files or uploads, and by HR's review; HR record saves keep the stored values.
export const proofStatuses = ['', 'required', 'submitted', 'verified', 'rejected'];
const leaveProof = { proofStatus: z.enum(proofStatuses).default(''), proofNote: z.string().max(2000).default(''), proofReviewedBy: z.string().max(100).default(''), proofReviewedAt: z.string().max(40).default('') };
export const schemas = {
  employees: z.object({ id, name: text, draft: flag.default(false), department: z.string().trim().max(1000), monthlySalary: money.positive().nullable(), startDate: optionalDate, endDate: optionalDate, active: flag, restDays: z.array(z.number().int().min(0).max(6)).max(6), scheduleStart: optionalTime, coveredOT: flag, coveredNSD: flag, coveredHoliday: flag, covered13th: flag, leaveEligibility: z.array(id).max(100) }).strict().refine(v => v.draft || (v.monthlySalary !== null && v.startDate && v.department && v.scheduleStart), 'Complete salary, employment start date, department and schedule before activating payroll.').refine(v => !v.draft || !v.active, 'Draft employees cannot be active.').refine(v => !v.endDate || (v.startDate && v.endDate >= v.startDate), 'End date precedes start date'),
  attendance: z.object({ id, employeeId: id, date, status: z.enum(['present', 'absent', 'off', 'official-business', 'rest-day-swap']), scheduledIn: time, timeIn: optionalTime, timeOut: optionalTime, endNextDay: flag, breaks: z.array(z.object({ start: text, end: text }).strict()).max(10), approved: flag, offsetMinutes: z.number().int().min(0).max(1440), exception: flag, explanation: z.string().max(1000), holidayEligible: flag }).strict().refine(v => v.status !== 'rest-day-swap' || v.explanation.trim().length >= 3, 'A rest-day swap must say which rest day was worked instead.').refine(v => v.status !== 'present' || (v.timeIn && v.timeOut), 'Present attendance requires clock-in and clock-out').refine(v => !(v.exception || v.offsetMinutes > 0) || v.explanation.trim(), 'Approved exceptions and offsets need an explanation'),
  leaveTypes: z.object({ id, name: text, paid: flag, category: z.enum(['statutory', 'company']), entitledDays: z.number().min(0).max(366), minServiceMonths: z.number().int().min(0).max(1200), eligibility: text, accrual: z.enum(['annual', 'monthly', 'none']), dayBasis: z.enum(['calendar', 'working']), carryOverDays: z.number().min(0).max(366), expirationMonths: z.number().int().min(1).max(12), documentsRequired: flag, approvalRequired: flag, affectsPayroll: flag, includedIn13th: flag, balanceRequired: flag }).strict(),
  leaves: z.object({ id, employeeId: id, typeId: id, startDate: date, endDate: date, days: z.number().positive().max(366), countedDates: z.array(date).max(366).optional(), reason: text, documentReference: z.string().max(1000), status: z.enum(['pending', 'approved', 'rejected', 'cancelled']), eligibilityVerified: flag, ...leaveProof }).strict().refine(v => v.endDate >= v.startDate, 'Leave end date precedes start date'),
  holidays: z.object({ id, date, name: text, kind: z.enum(['special', 'regular', 'double', 'other', 'ordinary']), basis: text }).strict(),
  // Company deductions defined by HR/Admin: any name, a fixed amount, and when it applies.
  deductions: z.object({ id, employeeId: id, name: z.string().trim().min(1).max(80), amount: money.positive(), schedule: z.enum(['once', 'every-cutoff', 'first-cutoff', 'second-cutoff']), startDate: date, endDate: z.union([date, z.literal('')]).default(''), active: flag, notes: z.string().max(1000).default('') }).strict().refine(v => !v.endDate || v.endDate >= v.startDate, 'The end date must be on or after the start date.'),
  loans: z.object({ id, employeeId: id, type: z.enum(['SSS Loan', 'Pag-IBIG Loan', 'Salary Loan', 'Other Company Loan']), reference: text, original: money.positive(), balance: money, monthlyAmortization: money.positive(), perPayroll: money.positive(), startDate: date, endDate: date, terms: z.number().int().positive().max(1200), remainingTerms: z.number().int().min(0).max(1200), authorized: flag }).strict().refine(v => v.balance <= v.original && v.remainingTerms <= v.terms && v.endDate >= v.startDate, 'Invalid loan balance, terms, or dates'),
  adjustments: z.object({ id, employeeId: id, date, kind: z.enum(['allowance', 'additional', 'otherDeduction']), amount: money.positive(), reason: text, approved: flag, includedIn13th: flag }).strict(),
  rules: z.object({ id, effectiveDate: date, basis: text, approvedBy: z.string().max(100), updatedAt: z.string().max(100), ordinaryOT: z.number().min(1).max(10), rest: z.number().min(1).max(10), premiumOT: z.number().min(1).max(10), special: z.number().min(1).max(10), specialRest: z.number().min(1).max(10), regular: z.number().min(1).max(10), double: z.number().min(1).max(10), other: z.number().min(0).max(10), nsd: z.number().min(0).max(1), specialUnworked: z.number().min(0).max(10), regularUnworked: z.number().min(0).max(10), doubleUnworked: z.number().min(0).max(10), otherUnworked: z.number().min(0).max(10), normalHours: z.number().min(1).max(8), dailyDivisor: z.number().positive().max(366), hourlyDivisor: z.number().positive().max(24), workdaysPerMonth: z.number().positive().max(31), graceMinutes: z.number().int().min(0).max(120), deductLate: flag, deductUndertime: flag, cutoff: z.enum(['monthly', 'semi-monthly']), contributionTiming: z.enum(['split', 'first', 'second']).default('split'), includeHolidayBaseIn13th: flag, contributionsReviewed: flag, calendarReviewedYears: z.array(z.number().int().min(2000).max(2200)).max(200), thirteenthTaxExemption: money, contributions: z.object({ SSS: z.array(bracket).max(200), PhilHealth: z.array(bracket).max(200), 'Pag-IBIG': z.array(bracket).max(200) }).strict(), taxBrackets: z.array(bracket).max(100), contributionBasis: z.literal('monthly-salary'), taxBasis: z.literal('gross-less-contributions') }).strict(),
};
// employeeIds narrows a payroll to chosen people (e.g. one employee); omitted means everyone eligible.
export const previewSchema = z.object({ start: date, end: date, pay13th: flag.default(false), employeeIds: z.array(id).min(1).max(500).optional() }).strict();
export const postSchema = previewSchema.extend({ fingerprint: z.string().regex(/^[a-f0-9]{64}$/) });
export const userSchema = z.object({ username: z.string().trim().regex(/^[A-Za-z0-9_.@-]{3,80}$/), password: z.string().min(12).max(200), role: z.enum(['admin', 'hr', 'payroll', 'viewer', 'employee']), employeeId: id.optional() }).strict().refine(v => v.role === 'employee' ? !!v.employeeId : !v.employeeId, 'Employee accounts require an Employee ID; staff accounts must not have one.');
